### PR TITLE
SUIT-8973 Improve test launcher device logs some fixes after code review

### PR DESCRIPTION
**Pull request by AntonSBilan**

### CODE REVIEW

**Comment by andriichumak** [comment]
@givehug Please, resolve conflicts

**Comment by givehug** [comment]
@AntonSBilan can you also please update UT for launcherLoggerHelper.js and testLauncherHelper.js, they poorly covered, and overall coverage barely reaches 95%.

**Comment by andriichumak** [comment]
@AntonSBilan Option `--logDir` must follow our naming convention. All other names are written with dash when defined from cli. Also, it shows up only if I run `suitest --help`. This is wrong. It shouldn't show up here, but when I call `suitest interactive --help` or `suitest automated --help`

**Comment by andriichumak** [comment]
Log directory must be normalised and logged as absolute path for easier debugging. E.g. If user wants to use relative path, showing absolute back to him would prevent a lot of questions in case it didn't work for some reason. E.g. I tried `suitest --logDir ./ automated npm test` and got this log output:
`Device 458156cd> Logs for device: 458156cd-9e13-4f64-a182-c9a16187fa65 will be written to .//458156cd-9e13-4f64-a182-c9a16187fa65.log`

Instead I should be seeing:
`Device 458156cd> Logs for device: 458156cd-9e13-4f64-a182-c9a16187fa65 will be written to`
`Device 458156cd> /Users/andrii/WebStormProjects/suitest-js-api/demo/458156cd-9e13-4f64-a182-c9a16187fa65.log`

**Comment by andriichumak** [comment]
@AntonSBilan could you please check UT exception

**Comment by AntonSBilan** [comment]
@andriichumak locally everything works

**Comment by andriichumak** [comment]
OK, after re-run its OK. We need to make out UT more reliable. We'll do that during next maintenance phase.

**Pull request merged**
